Feature/auth
GreenpixDev/ShiftAndroid pull request #5
Opened 2022-07-07 15:58 UTC by MaksimAkimov2003

первая версия регистрационного активити и активити входа

2022-07-07 17:11 UTC, GreenpixDev requested changes
## Нужны правки, а так молодец!

Помечать прочитанные или решеные комментарии можно так:
![image](https://user-images.githubusercontent.com/58062046/177831444-6edcaf27-dfa2-4c12-9d5a-806d44deacb2.png)

Ещё есть обязательные исправления в виде галочек:
![image](https://user-images.githubusercontent.com/58062046/177831531-6f2e3d0c-a8ea-45b1-949b-4bdc64800755.png)

Для правок просто продолжай пушить в свою ветку

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
> +private lateinit var binding: ActivityMainBinding
Почему у тебя это поле не внутри класса активити?

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
> +        """^[a-zA-Z][a-zA-Z0-9-_\.]{1,20}${'$'}""".toRegex() //регулярка для логина
- [ ] Эти строчки кода у тебя не используются в методе. Убери их.

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
> +        if ((!passwordString.matches(Regex("""^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).*${'$'}""")))) {
Регулярочку лучше вынести в константы, вот так:
```kotlin
companion object {
        
      private val PASSWORD_REGEX = Regex("""^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).*${'$'}""")
        
}

// ...

if (!passwordString.matches(PASSWORD_REGEX))
```

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
> +            passwordErrorToast.show()
Я бы тут добавил `return`, чтобы не проверялись сразу два условия - достаточно невыполнения одного условия, чтобы не дать пользователю авторизоваться.

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
> +                "Пароль должен содержать строчные и прописные латинские буквы, цифры",
Текст лучше брать из файла `strings.xml`

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
> +                "Логин должен состоять из букв и цифр, первый символ обязательно буква, ограничение 20 символов",
Текст лучше брать из файлы `strings.xml`

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
> +private fun TextInputLayout.onSwipeRight() {
- [ ] Этот метод не используется. Убери.

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
>  class MainActivity : AppCompatActivity() {
- [ ] Надо переименовать в `LoginActivity`. И xml активити соответственно.

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/res/layout/activity_main.xml
> +        app:endIconMode="password_toggle"
А нужна ли логину кнопка скрытия? Для пароля то понятно, но логину зачем?
![image](https://user-images.githubusercontent.com/58062046/177829830-170628a8-dd13-4c50-8d95-5b334542c198.png)

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/res/layout/activity_main.xml
> +        <com.google.android.material.textfield.TextInputEditText
Есть проблема - когда я нажимаю `Enter`, то вместо того, чтобы ввести логин, я делаю отступ. Мне кажется, что это неверная стратегия (где ты видел логины с отступами). Думаю это нужно исправить.

Я предлагаю вариант с вьюшкой `EditView`:
```xml
<EditText
    android:id="@+id/login"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:hint="Login"
    android:inputType="textPersonName" />
```

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/res/layout/activity_main.xml
> +        <com.google.android.material.textfield.TextInputEditText
Такая же проблема, что и с логином. 

Я предлагаю вариант с вьюшкой `EditView`:
```xml
<EditText
    android:id="@+id/login"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:hint="Login"
    android:inputType="textPersonName" />
```

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/res/layout/activity_registration.xml
> +        <com.google.android.material.textfield.TextInputEditText
Такая же проблема, что и в авторизации, смотри мои комментарии выше.

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/res/layout/activity_registration.xml
> +        <com.google.android.material.textfield.TextInputEditText
Такая же проблема, что и в авторизации, смотри мои комментарии выше.

2022-07-07 17:11 UTC, GreenpixDev commented on app/src/main/res/layout/activity_registration.xml
> +        <com.google.android.material.textfield.TextInputEditText
Такая же проблема, что и в авторизации, смотри мои комментарии выше.

2022-07-08 11:02 UTC, SHADESAVE commented on app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
> +        if ((!passwordString.matches(Regex("""^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).*${'$'}""")))) {
Или так:

```
private companion object {
        
     val PASSWORD_REGEX = Regex("""^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).*${'$'}""")
        
}
```

2022-07-14 13:00 UTC, GreenpixDev reviewed
Почему не используешь MVP паттерн?

2022-07-14 13:00 UTC, GreenpixDev commented on app/src/main/java/ru/cft/shift/scheduler/EventActivity.kt
> +        val str = arrayOf<String>("СР, 6 Июля","ЧТ, 7 Июля", "ПТ, 8 Июля")
Такие вещи нужно заносить в константы или в файл `strings.xml`

2022-07-14 13:00 UTC, GreenpixDev commented on app/src/main/java/ru/cft/shift/scheduler/EventActivity.kt
> +        var year = 2022
Такие вещи нужно заносить в константы или в файл strings.xml

2022-07-14 15:34 UTC, merged

2022-07-14 16:37 UTC, MaksimAkimov2003 commented on app/src/main/java/ru/cft/shift/scheduler/EventActivity.kt
> +        val str = arrayOf<String>("СР, 6 Июля","ЧТ, 7 Июля", "ПТ, 8 Июля")
это не константы, они меняются в ходе программы(показатели даты, часов и минут в Data Picker